name: Deploy to staging
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: deploy theme via rsync
        run: |
          rsync -rvz \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude=".github" \
            ${GITHUB_WORKSPACE}/* \
            ${{ secrets.STAGING_REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
